config/routes.rb
Rails.application.routes.draw do
  root "pages#home"
  devise_for :users, module: "users", skip: [:sessions]
  devise_scope :user do
    get "login" => "users/sessions#new", as: :new_user_session
    post "login" => "users/sessions#create", as: :user_session
    delete "logout" => "users/sessions#destroy", as: :destroy_user_session
    get "register" => "users/registrations#new", as: :register
    get ":username/profile" => "pages#profile", as: :profile
    get ":username/profile/edit" => "users/registrations#edit", as: :profile_edit
  end
  scope ":username" do
    get "dashboard" => "pages#dashboard"
    resources :categories, except: [:index] do
      resources :tasks, except: [:index]
      patch "/tasks/:id/toggle" => "tasks#toggle", as: :task_toggle
    end
  end
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :category
  validates :name, presence: true, length: { minimum: 3 }
  validates :details, presence: true, length: { minimum: 5 }
  validates :deadline, comparison: { greater_than: DateTime.current }
  validates :completed, inclusion: [true, false]
  validates :overdue, inclusion: [true, false]
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :authenticate_user!
  before_action :restrict_account
  before_action :toggle_overdue, only: [:show]
  before_action :set_category
  before_action :set_task, only: [:show, :edit, :update, :destroy, :toggle]
  after_action :reset_overdue, only: [:update]

  def show
  end

  def new
    @task = @category.tasks.build
  end

  def create
    @task = @category.tasks.build(task_params)
    if @task.save
      @category.update(updated_at: DateTime.current)
      flash[:notice] = "Task has been added"
      redirect_to category_task_path(current_user.username, @category, @task)
    else
      render :new, status: :unprocessable_entity
    end
  end
  
  def edit
  end

  def update
    if @task.update(task_params)
      @category.update(updated_at: DateTime.current)
      flash[:notice] = "Task has been updated"
      redirect_to category_task_path(current_user.username, @category, @task)
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @task.destroy
    flash[:alert] = "Task has been removed"
    redirect_to category_path(current_user.username, @category), status: :see_other
  end

  def toggle
    @task.completed = !@task.completed
    @task.save(validate: false)
    msg = "Task marked "
    @task.completed ? msg += "complete" : msg += "incomplete"
    flash[:notice] = msg
    redirect_to category_task_path(current_user.username, @category, @task), status: :see_other
  end


  private
  def set_category
    @category = current_user.categories.find(params[:category_id])
  end

  def set_task
    @task = @category.tasks.find(params[:id])
  end

  def reset_overdue
    @task.update(overdue: false);
  end

  def task_params
    params.require(:task).permit(:name, :details, :deadline, :completed, :overdue)
  end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/tasks/_form.html.erb
<%= form_with(model: [@category, @task]) do |f| %>
  <div class="p-3">
    <%= f.label :name, class: "form-label" %>
    <%= f.text_field :name, class: "form-control" %>
    <div class="container p-2">
      <% @task.errors.full_messages_for(:name).each do |msg| %>
        <p class="m-0 text-danger"><%= msg %></p>
      <% end %>
    </div>
  </div>
  <div class="p-3">
    <%= f.label :details, class: "form-label" %> 
    <%= f.text_area :details, class: "form-control" %>
    <div class="container p-2">
      <% @task.errors.full_messages_for(:details).each do |msg| %>
        <p class="m-0 text-danger"><%= msg %></p>
      <% end %>
    </div>
  </div>
  <div class="p-3">
    <%= f.label :deadline, class: "form-label" %>
    <%= f.datetime_local_field :deadline, class: "form-control" %>
    <div class="container p-2">
      <% @task.errors.full_messages_for(:deadline).each do |msg| %>
        <p class="m-0 text-danger"><%= msg %></p>
      <% end %>
    </div>
  </div>
  <div class="p-3">
    <%= f.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/tasks/_form_create.html.erb
<%= form_with(model: [@category, @task], url: category_tasks_path(current_user.username, @category)) do |f| %>
  <div class="p-3">
    <%= f.label :name, class: "form-label" %>
    <%= f.text_field :name, class: "form-control" %>
    <div class="container p-2">
      <% @task.errors.full_messages_for(:name).each do |msg| %>
        <p class="m-0 text-danger"><%= msg %></p>
      <% end %>
    </div>
  </div>
  <div class="p-3">
    <%= f.label :details, class: "form-label" %> 
    <%= f.text_area :details, class: "form-control" %>
    <div class="container p-2">
      <% @task.errors.full_messages_for(:details).each do |msg| %>
        <p class="m-0 text-danger"><%= msg %></p>
      <% end %>
    </div>
  </div>
  <div class="p-3">
    <%= f.label :deadline, class: "form-label" %>
    <%= f.datetime_local_field :deadline, class: "form-control" %>
    <div class="container p-2">
      <% @task.errors.full_messages_for(:deadline).each do |msg| %>
        <p class="m-0 text-danger"><%= msg %></p>
      <% end %>
    </div>
  </div>
  <div class="p-3">
    <%= f.submit class: "btn btn-primary"%>
  </div>
<% end %>

app/views/tasks/_form_update.html.erb
<%= form_with(model: [@category, @task], url: category_task_path(current_user.username, @category, @task)) do |f| %>
  <div class="p-3">
    <%= f.label :name, class: "form-label" %>
    <%= f.text_field :name, class: "form-control" %>
    <div class="container p-2">
      <% @task.errors.full_messages_for(:name).each do |msg| %>
        <p class="m-0 text-danger"><%= msg %></p>
      <% end %>
    </div>
  </div>
  <div class="p-3">
    <%= f.label :details, class: "form-label" %> 
    <%= f.text_area :details, class: "form-control" %>
    <div class="container p-2">
      <% @task.errors.full_messages_for(:details).each do |msg| %>
        <p class="m-0 text-danger"><%= msg %></p>
      <% end %>
    </div>
  </div>
  <div class="p-3">
    <%= f.label :deadline, class: "form-label" %>
    <%= f.datetime_local_field :deadline, class: "form-control" %>
    <div class="container p-2">
      <% @task.errors.full_messages_for(:deadline).each do |msg| %>
        <p class="m-0 text-danger"><%= msg %></p>
      <% end %>
    </div>
  </div>
  <div class="p-3">
    <%= f.submit class: "btn btn-primary"%>
  </div>
<% end %>

app/views/tasks/_modal.html.erb
<div class="modal fade" id="taskModal" tabindex="-1" aria-labelledby="taskModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="taskModalLabel">Confirmation</h5>
      </div>
      <div class="modal-body">
        This will delete the current task. Proceed?
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
        <%= link_to "Continue", category_task_path(current_user.username, @category, @task), data: { turbo_method: :delete }, class: "btn btn-primary" %>
      </div>
    </div>
  </div>
</div>

app/views/tasks/_task.html.erb
<div class="container">
  <% if @tasks.empty? %>
    <div class="row p-3 bg-white shadow" style="height: 10vh;">
      <div class="col border border-2 d-flex justify-content-center align-items-center bg-secondary bg-opacity-10">
        No available tasks
      </div>
    </div>
  <% end %>
  <% @tasks.each do |task| %>
    <div class="row bg-white shadow my-2 ">
      <% if task.completed %>
        <%= link_to category_task_toggle_path(current_user.username, @category, task), data: { turbo_method: :patch }, class: "col-2 col-lg-1 btn btn-secondary border-0 rounded-0 d-flex justify-content-center align-items-center", style: "background-color: #{@category.theme_color}" do %>
          <i class="bi bi-check-circle-fill text-white" style="font-size: 1.25em;"></i>
        <% end %>
      <% else %>
        <%= link_to category_task_toggle_path(current_user.username, @category, task), data: { turbo_method: :patch }, class: "col-2 col-lg-1 btn btn-secondary border-0 rounded-0 d-flex justify-content-center align-items-center" do %>
          <i class="bi bi-app text-white"style="font-size: 1.25em;"></i>
        <% end %>
      <% end %>
      <%= link_to category_task_path(current_user.username, @category, task), class: "col py-3 px-3 text-decoration-none text-reset #{"bg-danger bg-opacity-10" if !task.completed && task.overdue }" do %>
        <p class="fs-5 "><%= task.name %></p>
        <p class="m-0 text-muted">
          <span class="<%= "text-danger" if task.deadline.today? %>"><%= task.deadline.to_fs(:long) %></span> 
        </p>
      <% end %>
    </div>
  <% end %>
</div>

app/views/tasks/edit.html.erb
<%= render "layouts/components/breadcrumb", profile: false, category: @category ||= nil, task: @task ||= nil %>

<div class="container my-4">
  <div class="container p-3 bg-white shadow">
    <div class="d-flex justify-content-between align-items-center">
      <h1>Edit Task</h1>
      <%= link_to "Cancel", category_task_path(current_user.username, @category, @task), class: "btn btn-outline-primary btn-sm" %>
    </div>
    <%= render "form_update" %>
  </div>
</div>

app/views/tasks/new.html.erb
<%= render "layouts/components/breadcrumb", profile: false, category: @category ||= nil, task: @task ||= nil %>

<div class="container my-4">
  <div class="container p-3 bg-white shadow">
    <div class="d-flex justify-content-between align-items-center">
      <h1>Create Task</h1>
      <%= link_to "Cancel", category_path(current_user.username, @category), class: "btn btn-outline-primary btn-sm" %>
    </div>
    <%= render "form_create" %>
  </div>
</div>

app/views/tasks/show.html.erb
<%= render "layouts/components/breadcrumb", profile: false, category: @category ||= nil, task: @task ||= nil %>

<div class="container my-4">
  <div class="container p-3 my-3 bg-white shadow" style="border-left: 15px solid <%= @category.theme_color %>;">
    <h1><%= @task.name %></h1>
    <p>
      <% if @task.completed %>
        <span class="badge rounded-pill bg-success">COMPLETED</span>
      <% elsif @task.overdue %>
        <span class="badge rounded-pill bg-danger">OVERDUE</span>
      <% else %>
        <span class="badge rounded-pill bg-secondary">IN PROGRESS</span>
      <% end %>
    </p>
    <p class="text-muted">Deadline: <%= @task.deadline.to_fs(:long) %></p>
    <div class="p-3">
      <p><%= @task.details %></p>
    </div>
    <div class="d-flex justify-content-between">
      <div>
        <%= link_to edit_category_task_path(current_user.username, @category, @task), class: "btn btn-outline-primary btn-sm" do %>
          <i class="bi bi-pencil-square"></i> Edit
        <% end %>
        <button class="btn btn-outline-primary btn-sm" data-bs-toggle="modal" data-bs-target="#taskModal">
          <i class="bi bi-trash-fill"></i> Delete
        </button>
      </div>
      <div>
        <% if @task.completed %>
          <%= link_to "Mark Incomplete", category_task_toggle_path(current_user.username, @category, @task), data: { turbo_method: :patch }, class: "btn btn-secondary btn-sm" %>
        <% else %>
         <%= link_to "Mark Complete", category_task_toggle_path(current_user.username, @category, @task), data: { turbo_method: :patch }, class: "btn btn-success btn-sm" %>
        <% end %>
      </div>
    </div>
  </div>
  <%= render "modal" %>
</div>