config/routes.rb
Rails.application.routes.draw do
  root "pages#home"
  devise_for :users, module: "users", skip: [:sessions]
  devise_scope :user do
    get "login" => "users/sessions#new", as: :new_user_session
    post "login" => "users/sessions#create", as: :user_session
    delete "logout" => "users/sessions#destroy", as: :destroy_user_session
    get "register" => "users/registrations#new", as: :register
    get ":username/profile" => "pages#profile", as: :profile
    get ":username/profile/edit" => "users/registrations#edit", as: :profile_edit
  end
  scope ":username" do
    get "dashboard" => "pages#dashboard"
    resources :categories, except: [:index] do
      resources :tasks, except: [:index]
      patch "/tasks/:id/toggle" => "tasks#toggle", as: :task_toggle
    end
  end
end

app/views/pages/_category.html.erb
<div class="container p-2">
  <% if obj.empty? %>
    <div class="row p-3 bg-white shadow" style="height: 10vh;">
      <div class="col border border-2 d-flex justify-content-center align-items-center bg-secondary bg-opacity-10">
        No Categories
      </div>
    </div>
  <% end %>
  <% @themes.each do |color| %>
    <div class="row g-2 mx-1 my-2">
      <% obj.each do |obj| %>
        <% if obj.theme_color == color %>
        <div class="col-12 col-md-6 col-xl-4">
          <%= link_to category_path(current_user.username, obj), class: "text-decoration-none text-reset" do %>
            <div class="p-3 text-white shadow" style="background-color: <%= color %>;">
              <p class="fs-5 mb-0 text-white <%= "text-opacity-50" if obj.tasks.count == 0 %> text-end">
                <%= obj.tasks.count %> <%= "task".pluralize(obj.tasks.count) %>
              </p>
              <p class="fs-2 fw-bold text-wrap text-capitalize"><%= obj.name %></p>
            </div>
          <% end %>
        </div>
        <% end %>
      <% end %>
    </div>
  <% end %>
</div>

app/views/pages/_overview.html.erb
<div class="container pb-2 mt-0 mb-4 bg-white shadow">
  <div class="nav nav-pills mb-1 row" id="pills-tab" role="tablist">
    <button class="nav-link active col rounded-0" id="pills-today-tab" data-bs-toggle="pill" data-bs-target="#pills-today" type="button" role="tab" aria-controls="pills-home" aria-selected="true">
      <i class="bi bi-calendar-check-fill"></i> Today
    </button>
    <button class="nav-link col rounded-0" id="pills-overdue-tab" data-bs-toggle="pill" data-bs-target="#pills-overdue" type="button" role="tab" aria-controls="pills-profile" aria-selected="false">
      <i class="bi bi-clock-fill"></i> Overdue
    </button>
  </div>
  <div class="tab-content py-2" id="pills-tabContent">
    <div class="tab-pane fade show active" id="pills-today" role="tabpanel" aria-labelledby="pills-today-tab" tabindex="0">
      <% if @tasks.empty? %>
        <div class="p-3 m-2 bg-secondary bg-opacity-10 border border-2 text-center">
          No scheduled tasks
        </div>
      <% end %>
      <% @tasks.each do |task| %>
          <%= link_to category_task_path(current_user.username, task.category_id, task), class: "text-decoration-none" do %>
            <div class="px-3 pt-3 pb-2 m-2 bg-secondary bg-opacity-10 border border-2 text-primary">
              <p><%= task.name %></p>
              <p class="fw-light text-end text-muted mb-0"><%= task.deadline.to_fs(:long) %></p>
            </div>
        <% end %>
      <% end %>
    </div>
    <div class="tab-pane fade" id="pills-overdue" role="tabpanel" aria-labelledby="pills-overdue-tab" tabindex="0">
      <% if @tasks_overdue.empty? %>
        <div class="p-3 m-2 bg-secondary bg-opacity-10 border border-2 text-center">
          No overdue tasks
        </div>
      <% end %>
      <% @tasks_overdue.each do |overdue| %>
        <%= link_to category_task_path(current_user.username, overdue.category_id, overdue.id), class: "text-decoration-none" do %>
          <div class="px-3 pt-3 pb-2 m-2 bg-secondary bg-opacity-10 border border-2 text-danger">
            <p><%= overdue.name %></p>
            <p class="fw-light text-end text-muted mb-0"><%= overdue.deadline.to_fs(:long) %></p>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/pages/_profile.html.erb
<div class="container mb-4 shadow bg-white">
  <div class="row py-1 d-flex align-items-center">
      <%= link_to profile_path(current_user.username), class: "col-3 col-lg-2 p-3 d-flex justify-content-center align-items-center" do %>
      <img class="img-fluid" src="https://avatars.dicebear.com/api/avataaars/<%= current_user.username%>.svg?style=circle&&eyes=default&&mouth=smile&&backgroundColor=%239f86c0" alt="Default Avatar">
      <% end %>
    <div class="col px-4 border-start border-2 border-secondary ">
      <p class="fw-bold fs-4 mb-0 col-auto"><%= current_user.first_name.strip %> <%= current_user.last_name.strip %></p>
      <p class="text-muted fs-5 col">@ <%= current_user.username.strip %></p>
      <% unless current_user.bio.empty? %>
        <p class="d-none d-xl-block fw-light fs-6 col-12"><%= current_user.bio %></p>
      <% else %>
        <p class="d-none d-xl-block text-muted fs-6 col-12">Tell us something about yourself!</p>
      <% end %>
    </div>
  </div>
</div>

app/views/pages/dashboard.html.erb
<%= render "layouts/components/breadcrumb", profile: false, category: @category ||= nil, task: @task ||= nil %>

<div class="container my-4">
  <%= render "profile" %>
  <p class="pb-1 px-2 h3 text-muted">Overview</p>
  <%= render "overview" %>
  <div class="container px-2 d-flex justify-content-between align-items-center">
    <p class="h3 text-muted">All Categories</p>
    <%= link_to "Add Category", new_category_path(current_user.username), class: "btn btn-success" %>
  </div>
  <%= render "category", obj: @categories %>
</div>

app/views/pages/home.html.erb
<div class="container my-4 d-flex justify-content-center">
  <div class="col p-3 bg-primary text-white shadow">
    <h1>Welcome to Pluma</h1>
    <hr>
    <p class="p-3 mb-5">Organize day-to-day tasks and save time for the things that matter to you most.</p>
    <div class="d-flex justify-content-between">
      <a href="https://github.com/RJAA-25/Journal-App" target="_blank" class="btn btn-light text-primary"><i class="bi bi-github"></i></a>
      <a href=<%= current_user ? "/#{current_user.username}/dashboard" : "/login" %> class="btn btn-light">
        <%= current_user ? "Go to Dashboard" : "Get Started" %>
      </a>
    </div>
  </div>
</div>

app/views/pages/profile.html.erb
<%= render "layouts/components/breadcrumb", profile: true, category: @category ||= nil, task: @task ||= nil %>

<div class="container my-4">
  <div class="container bg-white shadow">
    <div class="row p-3">
      <div class="col-lg col-lg-4 d-flex justify-content-center align-items-center">
        <img class="img-fluid" src="https://avatars.dicebear.com/api/avataaars/<%= current_user.username%>.svg?style=circle&&eyes=default&&mouth=smile&&backgroundColor=%239f86c0&&size=300" alt="Default Avatar">
      </div>
      <div class="col-lg col-lg-8 my-4">
        <div class="d-flex justify-content-between align-items-center">
          <h1>User Profile</h1>
          <%= link_to "Edit", profile_edit_path(current_user.username), class: "btn btn-outline-primary" %>
        </div>
        <div class="row my-3 px-3">
            <div class="col-4 text-muted">First Name</div>
            <div class="col-8"><%= @user.first_name %></div>
        </div>
        <div class="row my-3 px-3">
            <div class="col-4 text-muted">Last Name</div>
            <div class="col-8"><%= @user.last_name %></div>
        </div>
        <div class="row my-3 px-3">
            <div class="col-4 text-muted">Username</div>
            <div class="col-8"><%= @user.username %></div>
        </div>
        <div class="row my-3 px-3">
            <div class="col-4 text-muted">Email</div>
            <div class="col-8"><%= @user.email %></div>
        </div>
        <div class="row my-4 p-3 border border-2">
            <p class="text-muted">Bio</p>
            <p class="fw-light"><%= @user.bio.empty? ? "Tell us something about yourself!" : @user.bio %></p>
        </div>
      </div>
    </div>
  </div>
</div>