config/routes.rb
Rails.application.routes.draw do
  root "pages#home"
  devise_for :users, module: "users", skip: [:sessions]
  devise_scope :user do
    get "login" => "users/sessions#new", as: :new_user_session
    post "login" => "users/sessions#create", as: :user_session
    delete "logout" => "users/sessions#destroy", as: :destroy_user_session
    get "register" => "users/registrations#new", as: :register
    get ":username/profile" => "pages#profile", as: :profile
    get ":username/profile/edit" => "users/registrations#edit", as: :profile_edit
  end
  scope ":username" do
    get "dashboard" => "pages#dashboard"
    resources :categories, except: [:index] do
      resources :tasks, except: [:index]
      patch "/tasks/:id/toggle" => "tasks#toggle", as: :task_toggle
    end
  end
end

app/views/layouts/components/_alert.html.erb
<% if notice %>
  <div class="m-0 alert alert-success alert-dismissible fade show" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
<% end %>
<% if alert %>
  <div class="m-0 alert alert-danger alert-dismissible fade show" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
<% end %>

app/views/layouts/components/_breadcrumb.html.erb
<div class="container pt-3 px-3 border-2 border-bottom border-secondary bg-white sticky-top">
  <div aria-label="breadcrumb">
    <ol class="breadcrumb">
      <li class="breadcrumb-item <%= "active" if !profile && !category && !task %>">
        <% if !profile && !category && !task %>
          Dashboard
        <% else %>
          <%= link_to "Dashboard", dashboard_path(current_user.username) %>
        <% end %>
      </li>
      <% if profile %>
        <li class="breadcrumb-item <%= "active" if !category && !task %>">Profile</li>
      <% end %>
      <% if category %>
        <li class="breadcrumb-item <%= "active" if !task %>">
          <% if !task %>
            Category
          <% else %>
            <%= link_to "Category", category_path(current_user.username, category.id) %>
          <% end %>
        </li>
      <% end %>
      <% if task %>
        <li class="breadcrumb-item active">Task</li>
      <% end %>
    </ol>
  </div>
</div>

app/views/layouts/components/_category.html.erb
<div class="container p-2">
  <% if obj.empty? %>
    <div class="row p-3 bg-white shadow" style="height: 10vh;">
      <div class="col border border-2 d-flex justify-content-center align-items-center bg-secondary bg-opacity-10">
        No Categories
      </div>
    </div>
  <% end %>
  <% @themes.each do |color| %>
    <div class="row g-2 mx-1 my-2">
      <% obj.each do |obj| %>
        <% if obj.theme_color == color %>
        <div class="col-12 col-md-6 col-xl-4">
          <%= link_to category_path(obj), class: "text-decoration-none text-reset" do %>
            <div class="p-3 text-white shadow" style="background-color: <%= color %>;">
              <p class="fs-5 mb-0 text-white <%= "text-opacity-50" if obj.tasks.count == 0 %> text-end">
                <%# if obj.tasks.count == 0 %>
                  <%# No tasks assigned %>
                <%# else %>
                  <%= obj.tasks.count %> <%= "task".pluralize(obj.tasks.count) %>
                <%# end %>
              </p>
              <p class="fs-2 fw-bold text-wrap text-capitalize"><%= obj.name %></p>
            </div>
          <% end %>
        </div>
        <% end %>
      <% end %>
    </div>
  <% end %>
</div>

app/views/layouts/components/_footer.html.erb
<div class="container-fluid d-flex justify-content-center bg-dark text-light p-2 mx-auto">
  <div>Avion School Batch 18</div>
</div>

app/views/layouts/components/_navbar.html.erb
<nav class="navbar bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand text-light" href=<%= current_user ? "/#{current_user.username}/dashboard" : "/" %> >Pluma</a>
    <% if current_user %>
      <%= link_to "Log Out", destroy_user_session_path, data: { turbo_method: :delete }, class: "btn btn-danger" %>
    <% end %>
  </div>
</nav>