config/routes.rb
Rails.application.routes.draw do
  root "pages#home"
  devise_for :users, module: "users", skip: [:sessions]
  devise_scope :user do
    get "login" => "users/sessions#new", as: :new_user_session
    post "login" => "users/sessions#create", as: :user_session
    delete "logout" => "users/sessions#destroy", as: :destroy_user_session
    get "register" => "users/registrations#new", as: :register
    get ":username/profile" => "pages#profile", as: :profile
    get ":username/profile/edit" => "users/registrations#edit", as: :profile_edit
  end
  scope ":username" do
    get "dashboard" => "pages#dashboard"
    resources :categories, except: [:index] do
      resources :tasks, except: [:index]
      patch "/tasks/:id/toggle" => "tasks#toggle", as: :task_toggle
    end
  end
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :user
  has_many :tasks, dependent: :destroy
  validates :name, presence: true, length: { minimum: 3, maximum: 15 }
  validates :description, presence: true, length: { minimum: 5 }
  validates :theme_color, presence: true, inclusion: { in: ["#540D6E", "#9F86C0", "#C71F37", "#E36414", "#3A5A40", "#6A994E", "#3F37C9", "#4895EF"] }
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :authenticate_user!
  before_action :restrict_account
  before_action :toggle_overdue, only: [:show]
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  def show
    @tasks = @category.tasks
  end

  def new
    @category = current_user.categories.build
  end

  def create
    @category = current_user.categories.build(category_params)
    if @category.save
      flash[:notice] = "Category has been added"
      redirect_to category_path(current_user.username, @category)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    if @category.update(category_params)
      flash[:notice] = "Category has been updated"
      redirect_to category_path(current_user.username, @category)
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @category.destroy
    flash[:alert] = "Category has been deleted"
    redirect_to dashboard_path(current_user.username), status: :see_other
  end


  private
  def set_category
    @category = current_user.categories.find(params[:id])
  end

  def category_params
    params.require(:category).permit(:name, :description, :theme_color)
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_category.html.erb
<div class="container shadow">
  <div class="row p-4 text-white" style="background-color: <%= obj.theme_color %>;">
    <div class="col">
      <h1 class="pb-1 text-capitalize"><%= obj.name %></h1>
      <button class="btn btn-outline-light btn-sm" type="button" data-bs-toggle="collapse" data-bs-target="#categoryInfo" aria-expanded="false" aria-controls="categoryInfo">
        <i class="bi bi-info-circle-fill"></i> Info
      </button>
      <%= link_to edit_category_path(current_user.username, obj), class: "btn btn-outline-light btn-sm" do %>
        <i class="bi bi-pencil-square"></i> Edit
      <% end %>
      <button class="btn btn-outline-light btn-sm" data-bs-toggle="modal" data-bs-target="#categoryModal">
        <i class="bi bi-trash-fill"></i> Delete
      </button>
    </div>
    <div class="col-2">
      <p class="m-0 fs-1 text-end fw-bold"><%= obj.tasks.count %></p>
      <p class="m-0 text-end"><%= "task".pluralize(obj.tasks.count) %></p>
    </div>
  </div>
  <div class="row px-3 pt-3 pb-3 bg-white" style="border-style: solid; border-width: 2px; border-color: <%= obj.theme_color %>;">
    <div class="col collapse" id="categoryInfo">
      <p class="fs-light"><%= obj.description %></p>
      <p class="text-muted text-end">Updated <%= obj.updated_at.to_fs(:long) %></p>
    </div>
  </div>
</div>

app/views/categories/_form_create.html.erb
<%= form_with(model: @category, url: categories_path(current_user.username)) do |f| %>
  <div class="p-3">
    <%= f.label :name, class: "form-label" %>
    <%= f.text_field :name, class: "form-control" %>
    <div class="container p-2">
      <% @category.errors.full_messages_for(:name).each do |msg| %>
        <p class="m-0 text-danger"><%= msg %></p>
      <% end %>
    </div>
  </div>
  <div class="p-3">
    <%= f.label :description, class: "form-label" %>
    <%= f.text_area :description, class: "form-control" %>
    <div class="container p-2">
      <% @category.errors.full_messages_for(:description).each do |msg| %>
        <p class="m-0 text-danger"><%= msg %></p>
      <% end %>
    </div>
  </div>
  <div class="p-3">
    <%= f.label :theme_color, class: "form-label" %>
    <select name="category[theme_color]" id="category_theme_color" class="form-select">
      <option value="#540D6E" class="theme-1" <%= "selected" if @category.theme_color == "#540D6E" %>>Color 1: #540D6E</option>
      <option value="#9F86C0" class="theme-2" <%= "selected" if @category.theme_color == "#9F86C0" %>>Color 2: #9F86C0</option>
      <option value="#C71F37" class="theme-3" <%= "selected" if @category.theme_color == "#C71F37" %>>Color 3: #C71F37</option>
      <option value="#E36414" class="theme-4" <%= "selected" if @category.theme_color == "#E36414" %>>Color 4: #E36414</option>
      <option value="#3A5A40" class="theme-5" <%= "selected" if @category.theme_color == "#3A5A40" %>>Color 5: #3A5A40</option>
      <option value="#6A994E" class="theme-6" <%= "selected" if @category.theme_color == "#6A994E" %>>Color 6: #6A994E</option>
      <option value="#3F37C9" class="theme-7" <%= "selected" if @category.theme_color == "#3F37C9" %>>Color 7: #3F37C9</option>
      <option value="#4895EF" class="theme-8" <%= "selected" if @category.theme_color == "#4895EF" %>>Color 8: #4895EF</option>
    </select>
    <div class="container p-2">
      <% @category.errors.full_messages_for(:theme_color).each do |msg| %>
        <p class="m-0 text-danger"><%= msg %></p>
      <% end %>
    </div>
  </div>
  <div class="p-3">
    <%= f.submit  class: "btn btn-primary" %>
  </div>
<% end %>

app/views/categories/_form_update.html.erb
<%= form_with(model: @category, url: category_path(current_user.username, @category)) do |f| %>
  <div class="p-3">
    <%= f.label :name, class: "form-label" %>
    <%= f.text_field :name, class: "form-control" %>
    <div class="container p-2">
      <% @category.errors.full_messages_for(:name).each do |msg| %>
        <p class="m-0 text-danger"><%= msg %></p>
      <% end %>
    </div>
  </div>
  <div class="p-3">
    <%= f.label :description, class: "form-label" %>
    <%= f.text_area :description, class: "form-control" %>
    <div class="container p-2">
      <% @category.errors.full_messages_for(:description).each do |msg| %>
        <p class="m-0 text-danger"><%= msg %></p>
      <% end %>
    </div>
  </div>
  <div class="p-3">
    <%= f.label :theme_color, class: "form-label" %>
    <select name="category[theme_color]" id="category_theme_color" class="form-select">
      <option value="#540D6E" class="theme-1" <%= "selected" if @category.theme_color == "#540D6E" %>>Color 1: #540D6E</option>
      <option value="#9F86C0" class="theme-2" <%= "selected" if @category.theme_color == "#9F86C0" %>>Color 2: #9F86C0</option>
      <option value="#C71F37" class="theme-3" <%= "selected" if @category.theme_color == "#C71F37" %>>Color 3: #C71F37</option>
      <option value="#E36414" class="theme-4" <%= "selected" if @category.theme_color == "#E36414" %>>Color 4: #E36414</option>
      <option value="#3A5A40" class="theme-5" <%= "selected" if @category.theme_color == "#3A5A40" %>>Color 5: #3A5A40</option>
      <option value="#6A994E" class="theme-6" <%= "selected" if @category.theme_color == "#6A994E" %>>Color 6: #6A994E</option>
      <option value="#3F37C9" class="theme-7" <%= "selected" if @category.theme_color == "#3F37C9" %>>Color 7: #3F37C9</option>
      <option value="#4895EF" class="theme-8" <%= "selected" if @category.theme_color == "#4895EF" %>>Color 8: #4895EF</option>
    </select>
    <div class="container p-2">
      <% @category.errors.full_messages_for(:theme_color).each do |msg| %>
        <p class="m-0 text-danger"><%= msg %></p>
      <% end %>
    </div>
  </div>
  <div class="p-3">
    <%= f.submit  class: "btn btn-primary" %>
  </div>
<% end %>

app/views/categories/_modal.html.erb
<div class="modal fade" id="categoryModal" tabindex="-1" aria-labelledby="categoryModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="categoryModalLabel">Confirmation</h5>
      </div>
      <div class="modal-body">
        This will delete the current category and its associated tasks. Proceed?
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
        <%= link_to "Continue", category_path(current_user.username, @category), data: { turbo_method: :delete }, class: "btn btn-primary" %>
      </div>
    </div>
  </div>
</div>

app/views/categories/_validation.html.erb
<div>
  <% if @category.errors.any? %>
    <ul>
      <% @category.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  <% end %>
</div>

app/views/categories/edit.html.erb
<%= render "layouts/components/breadcrumb", profile: false, category: @category ||= nil, task: @task ||= nil %>

<div class="container my-4">
  <div class="container p-3 bg-white shadow">
    <div class="d-flex justify-content-between align-items-center">
      <h1>Edit Category</h1>
      <%= link_to "Cancel", category_path(current_user.username, @category), class: "btn btn-outline-primary btn-sm" %>
    </div>
    <%= render "form_update" %>
  </div>
</div>

app/views/categories/index.html.erb
<h1>All Categories</h1>
<%= link_to "New Category", new_category_path %>
<hr>

<% @categories.each do |category| %>
  <div style="border-bottom: 3px solid <%= category.theme_color %>;">
    <%= render "category", obj: category %>
    <%= link_to "View", category_path(category) %> 
  </div>
<% end %>

app/views/categories/new.html.erb
<%= render "layouts/components/breadcrumb", profile: false, category: @category ||= nil, task: @task ||= nil %>

<div class="container my-4">
  <div class="container p-3 bg-white shadow">
    <div class="d-flex justify-content-between align-items-center">
      <h1>Create Category</h1>
      <%= link_to "Cancel", dashboard_path(current_user.username), class: "btn btn-outline-primary btn-sm" %>
    </div>
    <%= render "form_create" %>
  </div>
</div>

app/views/categories/show.html.erb
<%= render "layouts/components/breadcrumb", profile: false, category: @category ||= nil, task: @task ||= nil %>

<div class="container my-4">
  <%= render "category", obj: @category %>
  <div class="container px-2 my-4 d-flex justify-content-between align-items-center">
    <p class="h3 text-muted">All Tasks</p>
    <%= link_to "Add Task", new_category_task_path(current_user.username, @category), class: "btn btn-success" %>
  </div>
  <%= render "tasks/task" %>
  <%= render "modal" %>
</div>